export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import { Button } from "@/components/ui/button";
import { LogOut } from "lucide-react";
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/ui/tooltip";
import UserMenu from "@/components/user-menu";
import Link from "next/link";

export const dynamic = "force-dynamic";

export default function AuthenticatedLayout({ children }) {
  return (
    <div className="w-full flex flex-col p-4">
      <nav className="flex justify-between w-full pb-4">
        <UserMenu />
        <form action="/auth/signout" method="post">
          <div className="ml-auto">
            <TooltipProvider>
              <Tooltip>
                <TooltipTrigger asChild>
                  <Button variant="outline" type="submit">
                    <LogOut></LogOut>
                  </Button>
                </TooltipTrigger>
                <TooltipContent>
                  <p>Sign Out</p>
                </TooltipContent>
              </Tooltip>
            </TooltipProvider>
          </div>
        </form>
      </nav>
      {children}
    </div>
  );
}
